openapi: 3.0.1
info:
  title: k8s-services-list
  description: Service to discover inner kubernetes cluster services.
  version: 1.3.3
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: /
    description: relative path
security: []
paths:
  /getDeploymentsAndServices:
    get:
      operationId: getDeploymentsAndServices
      summary: Get deployments and services list
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/res'
        '400':
          description: BAD REQUEST
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        '500':
          description: INTERNAL SERVER ERROR
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
components:
  schemas:
    res:
      type: object
      properties:
        data:
          type: object
    error:
      type: object
      properties:
        error:
          type: string
