{{- $MAIN_OBJECT_BLOCK := "configValues" -}}
{{- $COMPONENT_NAME := "backend" -}}
{{- $DATA := include "k8sServicesListData" . -}}

{{- define "k8sServicesListData" -}}
{{- $CONFIG_MANAGER_OBJECT := include "common.tplvalues.getGlobalObject" (dict "objName" "configManagment" "context" .) | fromYaml }}
{{- if not $CONFIG_MANAGER_OBJECT.enabled -}}
  REQUEST_PAYLOAD_LIMIT: {{ .Values.env.requestPayloadLimit | quote }}
  RESPONSE_COMPRESSION_ENABLED: {{ .Values.env.responseCompressionEnabled | quote }}
{{- end }}
  K8S_NAMESPACE: {{ include "common.names.namespace" . }}
  K8S_LOAD_CONFIG_FROM_CLUSTER: "true"
{{- end -}}

{{ include "mc-chart.configmap" (dict "MAIN_OBJECT_BLOCK" $MAIN_OBJECT_BLOCK "COMPONENT_NAME" $COMPONENT_NAME "DATA" $DATA "WITH_TELEMETRY_TRACING" false "WITH_TELEMETRY_METRICS" false "context" .)}}
