{{- $chartName := include "service-discovery.name" . -}}
{{- $tracingUrl := include "service-discovery.tracingUrl" . -}}
{{- $metricsUrl := include "service-discovery.metricsUrl" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ $chartName }}-configmap
data:
  REQUEST_PAYLOAD_LIMIT: {{ .Values.env.requestPayloadLimit | quote }}
  RESPONSE_COMPRESSION_ENABLED: {{ .Values.env.responseCompressionEnabled | quote }}
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  LOG_PRETTY_PRINT_ENABLED: {{ .Values.env.logPrettyPrintEnabled | quote }}
  {{ if .Values.env.tracing.enabled }}
  TELEMETRY_TRACING_ENABLED: 'true'
  TELEMETRY_TRACING_URL: {{ $tracingUrl }}
  {{ end }}
  {{ if .Values.env.metrics.enabled }}
  TELEMETRY_METRICS_ENABLED: 'true'
  TELEMETRY_METRICS_URL: {{ $metricsUrl }}
  {{ end }}
<<<<<<< HEAD
  K8S_NAMESPACE: {{.Values.kubernetes.namespace | quote}}
=======
  K8S_NAMESPACES: 
    {{- range $namespace := .Values.kubernetes.namespaces }}
    - {{ $namespace | quote}}
    {{- end }}
    - {{ $.Release.Namespace | quote }}
>>>>>>> cdf126ca071629292c2ded7f85624959d5eba732
  K8S_LOAD_CONFIG_FROM_CLUSTER: "true"
{{- end }}
