{{- $releaseName := .Release.Name -}}
{{- $chartName := include "service-discovery.name" . -}}
{{- $cloudProviderFlavor := include "service-discovery.cloudProviderFlavor" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $releaseName }}
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    environment: {{ include "service-discovery.environment" . }}
    release: {{ $releaseName }}
    {{- include "service-discovery.labels" . | nindent 4 }}
spec:
  {{- if eq $cloudProviderFlavor "minikube" }}
  type: NodePort
  {{- end }}
  ports:
    - port: {{ .Values.env.port }}
      targetPort: {{ .Values.env.targetPort }}
      protocol: {{ .Values.env.protocol }}
      name: http
      {{- if eq $cloudProviderFlavor "minikube" }}
      nodePort: {{ .Values.nodePort }}
      {{- end }}
  selector:
    app: {{ $chartName }}
    release: {{ $releaseName }}
    run: {{ $releaseName }}
    {{- include "service-discovery.selectorLabels" . | nindent 4 }}
{{- end }}
