apiVersion: v2
name: k8s-services-list
description: A Helm chart for service-discovery service
type: application
version: 1.9.0
appVersion: 1.9.0
dependencies:
- name: common
  version: 1.0.1
  repository: file://../../helm-common
