global:
  configManagment:
    enabled: false
  imageRegistry: acrarolibotnonprod.azurecr.io
  imagePullSecrets:
    - my-registry
  deploymentFlavor: openshift
  tlsCertificates:
    certificate:
    key:
    caCertificate:
  tracing:
    enabled: false
    url: http://localhost:55681/v1/traces
  metrics:
    enabled: false
    url: http://localhost:55681/v1/metrics
  environment: development
  releaseVersion: DUMMY_releaseVersion
  currentSubChart: DUMMY_currentSubChart

kubeVersion:
commonLabels:
commonAnnotations:
# ----------- initContainers ----------
volumePermissions:
  enabled: false
# ------ volumes and volumeMounts -----
persistence:
  enabled: false
# ----------- command/debug -----------
diagnosticMode:
  enabled: false
# --------- MAIN_OBJECT_BLOCK ---------
configValues:
  deploymentAnnotations:
    # collectord.io/index: '' # PROVIDE SPLUNK INDEX
  autoscaling:
    hpa:
      enabled: false
  replicaCount: 1
  podAnnotations:
    enabled: true
    resetOnConfigChange: true
    annotations: {}
  prometheus:
    scrape: false
  metrics:
    enabled: false
  tracing:
    enabled: false
  nodeAffinityPreset: {}
  podSecurityContext: {}
  # ----------- containers ------------
  image:
    repository: k8s-services-list
    tag: v1.1.4
    pullPolicy: Always
    debug: false
  containerSecurityContext:
    enabled: true
    runAsNonRoot: true
    runAsUser: 1000700000
  extraEnvVars:
    - name: SERVER_PORT
      value: '{{ .Values.configValues.containerPorts.http }}'
  extraEnvVarsCM: '{{ template "common.names.fullname" . }}'
  extraEnvVarsSecret:
  resources:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 50m
      memory: 200Mi
  containerPorts:
    http: 8080
    https: 443
  livenessProbe:
    enabled: true
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1
  readinessProbe:
    enabled : false
  startupProbe:
    enabled : false
env:
  logLevel: info
  logPrettyPrintEnabled: false
  responseCompressionEnabled: true
  requestPayloadLimit: 1mb
route:
  enabled: true
  annotations:
    haproxy.router.openshift.io/rewrite-target: /
  timeout:
    enabled: false
    duration: 60s
  hostname:
  path: /
  targetPort: http
  tls: 
    enabled: true
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
    useCerts: false
  extraRules:
ingress:
  enabled: false
  # apiVersion: ""
  # type: nginx-kubernetes
  # annotations: {}
  # pathType: Prefix
  # hostname: COMPONENT_NAME.local
  # extraHosts: []
  # extraPaths: []
  # path: /service-discovery
  # extraRules: []
  # extraTls: []
  # selfSigned: false
  # tls: true
  # cors:
  #   enabled: true
  #   origin: '*'
service:
  annotations: {}
  ports:
    http: 80
  protocol: TCP
serviceAccount:
  ## @param serviceAccount.create Specifies whether a ServiceAccount should be created
  ##
  create: true
  ## @param serviceAccount.name The name of the ServiceAccount to use.
  ## If not set and create is true, a name is generated using the common.names.fullname template
  ##
  name: ""
  ## @param serviceAccount.annotations Additional Service Account annotations (evaluated as a template)
  ##
  annotations: {}
rbac:
  ## @param rbac.create Specifies whether RBAC resources should be created
  ##
  create: true
  ## @param rbac.rules Custom RBAC rules to set
  ## e.g:
  ## rules:
  ##   - apiGroups:
  ##       - ""
  ##     resources:
  ##       - pods
  ##     verbs:
  ##       - get
  ##       - list
  ##
  rules:
    - apiGroups:
        - apps
      resources:
        - deployments
      verbs:
        - get 
        - watch
        - list
    - apiGroups: 
        - ""
      resources:
        - endpoints 
        - services
      verbs:
        - get 
        - watch
        - list
## PodSecurityPolicy configuration
## ref: https://kubernetes.io/docs/concepts/policy/pod-security-policy/
##
podSecurityPolicy:
  ## @param podSecurityPolicy.create Whether to create a PodSecurityPolicy. WARNING: PodSecurityPolicy is deprecated in Kubernetes v1.21 or later, unavailable in v1.25 or later
  ##
  create: false
  ## @param podSecurityPolicy.enabled Enable PodSecurityPolicy's RBAC rules
  ##
  enabled: false