global:
  cloudProvider: {}
  tracing: {}
  metrics: {}
  environment: ''
enabled: true
environment: development
replicaCount: 1
initialDelaySeconds: 60
nodePort: 30030
resetOnConfigChange: true
cloudProvider:
  dockerRegistryUrl: localhost:5001
  imagePullSecretName: my-registry-secret
  flavor: openshift
image:
  repository: k8s-services-list
  tag: v1.1.4
env:
  port: 80
  targetPort: 8080
  protocol: TCP
  logLevel: info
  logPrettyPrintEnabled: false
  responseCompressionEnabled: true
  requestPayloadLimit: 1mb
  tracing:
    enabled: false
    url: http://localhost:55681/v1/traces
  metrics:
    enabled: false
    url: http://localhost:55681/v1/metrics
resources:
  enabled: true
  value:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 50m
      memory: 200Mi
route:
  enabled: true
  host:
  path: /
  tls: true
  timeout:
    enabled: false
    duration: 60s
ingress:
  enabled: false
  type: nginx-kubernetes # supported values: 'nginx-org' | 'nginx-kubernetes'
  host:
  path: /
  cors:
    enabled: true
    origin: '*'
  tls:
    useExternal:
