global:
  configManagment:
    enabled: true
  imageRegistry: acrarolibotnonprod.azurecr.io
  imagePullSecrets:
    - my-registry
  deploymentFlavor: openshift
  tlsCertificates:
    certificate:
    key:
    caCertificate:
  tracing:
    enabled: false
    url: http://localhost:55681/v1/traces
  metrics:
    enabled: false
    url: http://localhost:55681/v1/metrics
  environment: development
  releaseVersion: DUMMY_releaseVersion
  currentSubChart: DUMMY_currentSubChart

kubeVersion:
commonLabels:
commonAnnotations:
# ----------- initContainers -----------
volumePermissions:
  enabled: false
# ------ volumes and volumeMounts ------
persistence:
  enabled: false
# ------------ command/debug -----------
diagnosticMode:
  enabled: false
configValues:
  extraEnvVars:
    - name: SERVER_PORT
      value: '{{ .Values.configValues.containerPorts.http }}'
  autoscaling:
    hpa:
      enabled: false
  podAnnotations:
    enabled: true
    resetOnConfigChange: true
    annotations: {}
  image:
    repository: k8s-services-list
    tag: v1.1.4
    pullPolicy: Always
  nodeAffinityPreset: {}
  podSecurityContext: {}
  containerSecurityContext: {}
  resourcesPreset: nano
  containerPorts:
    http: 8080
    https: 443
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled : false
  startupProbe:
    enabled : false
  replicaCount: 1
  prometheus:
    scrape: false
  metrics:
    enabled: false
  automountServiceAccountToken: false
enabled: true
environment: development
initialDelaySeconds: 60
nodePort: 30030
runAsUser: 1000700000
env:
  logLevel: info
  logPrettyPrintEnabled: false
  responseCompressionEnabled: true
  requestPayloadLimit: 1mb
resources:
  enabled: true
  value:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 50m
      memory: 200Mi
route:
  enabled: true
  annotations:
    haproxy.router.openshift.io/rewrite-target: /
  timeout:
    enabled: false
    duration: 60s
  hostname:
  path: /
  tls: 
    enabled: true
    useCerts: false
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  extraRules:
ingress:
  enabled: false
  # apiVersion: ""
  # type: nginx-kubernetes
  # annotations: {}
  # pathType: Prefix
  # hostname: COMPONENT_NAME.local
  # extraHosts: []
  # extraPaths: []
  # path: /service-discovery
  # extraRules: []
  # extraTls: []
  # selfSigned: false
  # tls: true
  # cors:
  #   enabled: true
  #   origin: '*'
service:
  annotations: {}
  ports:
    http: 80
  protocol: TCP
serviceAccount:
  ## @param serviceAccount.create Specifies whether a ServiceAccount should be created
  ##
  create: true
  ## @param serviceAccount.name The name of the ServiceAccount to use.
  ## If not set and create is true, a name is generated using the common.names.fullname template
  ##
  name: ""
  ## @param serviceAccount.annotations Additional Service Account annotations (evaluated as a template)
  ##
  annotations: {}
  ## @param serviceAccount.automountServiceAccountToken Automount service account token for the server service account
  ##
  automountServiceAccountToken: false

rbac:
  ## @param rbac.create Specifies whether RBAC resources should be created
  ##
  create: true
  ## @param rbac.rules Custom RBAC rules to set
  ## e.g:
  ## rules:
  ##   - apiGroups:
  ##       - ""
  ##     resources:
  ##       - pods
  ##     verbs:
  ##       - get
  ##       - list
  ##
  rules:
    - apiGroups:
        - apps
      resources:
        - deployments
      verbs:
        - get 
        - watch
        - list
    - apiGroups: 
        - ""
      resources:
        - endpoints 
        - services
      verbs:
        - get 
        - watch
        - list
## PodSecurityPolicy configuration
## ref: https://kubernetes.io/docs/concepts/policy/pod-security-policy/
##
podSecurityPolicy:
  ## @param podSecurityPolicy.create Whether to create a PodSecurityPolicy. WARNING: PodSecurityPolicy is deprecated in Kubernetes v1.21 or later, unavailable in v1.25 or later
  ##
  create: false
  ## @param podSecurityPolicy.enabled Enable PodSecurityPolicy's RBAC rules
  ##
  enabled: false